### PR TITLE
add new kb to gather Gitlab logs

### PR DESCRIPTION
**Pull request by sebasrevuelta**
# Thanks for improving Semgrep Docs 😀

### Please ensure

- [ ] A subject matter expert (SME) reviews the content
- [ ] A technical writer reviews the content or PR
- [x] This change has no security implications or else you have pinged the security team
- [ ] Redirects are added if the PR changes page URLs
- [ ] If you have changed any header tag links (doc/#this-kind-of-anchor), update all instances of that link

### CODE REVIEW

**Comment by armchairlinguist** [comment]
@sebasrevuelta would you be okay if I push some changes to the branch directly? Otherwise I can do the suggestions, but I don't want to make you just click a bunch of buttons when it might be easier to do direct changes.

**Comment by sebastianrevuelta** [comment]
@armchairlinguist absolutely yes, you can do whatever change and push to the branch directly! Thanks.

**Review by khorne3 — APPROVED** [review]
Thank you!

**Comment by armchairlinguist** [comment]
@khorne3 FYI I also updated, feel free to take a look at my changes and let me know if you have any concerns.

**Comment by khorne3** [comment]
@armchairlinguist Thank you -- I learn a lot from reading your additions!

**Comment by sebastianrevuelta** [comment]
Thanks @armchairlinguist @khorne3 for your valuable comments!

**Comment by s-santillan** [comment]
I think we can merge? No need for me to give a review as Katie is already the TW review and Alexis is the SME for this. :grinning: 

image

**Comment by armchairlinguist** [comment]
Worth it for the meme! I was surprised Sebas didn't merge, but I'll go ahead and do it!

**Pull request merged**
