### PR TITLE
add info to distinguish between fixed and removed findings (reliable fixed status)

### PR DESCRIPTION
**Pull request by khorne3**
# Thanks for improving Semgrep Docs 😀

### Please ensure

- [x] A subject matter expert (SME) reviews the content
- [x] A technical writer reviews the content or PR
- [x] This change has no security implications or else you have pinged the security team

### CODE REVIEW

**Review by s-santillan — APPROVED** [review]
LGTM!

**Comment by vivekkhimani** [comment]
Thanks for updating the docs. I can leave a comment on the PR too but I don’t think our “removed” status is ever exposed to the user. It is something that we use to “archive” the findings instead of permanently deleting them from the database. I am unsure though if users can get “removed” issues via our public API. That might be a good question for @daniel-bryant !

Except that, the fixed part looks great.

**Comment by khorne3** [comment]
@daniel-bryant do you know if users would be able to obtain information regarding removed findings from the API? If so, we'll want to add a note regarding this

**Comment by daniel-bryant** [comment]
Hey @khorne3. Hmm okay it's kind of interesting. So we [silently filter out `removed` findings from the list endpoint](https://github.com/semgrep/semgrep-app/blob/develop/server/semgrep_app/core_exp/findings/handlers/issue.py#L521), which means theoretically customers would never have `removed` findings returned. But we do list `removed` as a possible `state` https://semgrep.dev/api/v1/docs/#tag/Finding/operation/semgrep_app.core_exp.findings.handlers.issue.openapi_list_recent_issues.

**Pull request merged**
