### PR TITLE
Infobox on how to historical-scan for invalid/unvalidated findings

### PR DESCRIPTION
**Pull request by armchairlinguist**
By default we just do valid historical secrets (yay, ++ good) but maybe sometimes people are interested in all of them so let's give them the info on how to do that too.

### Please ensure

- [ ] A subject matter expert (SME) reviews the content
- [ ] A technical writer reviews the content or PR
- [x] This change has no security implications or else you have pinged the security team

### CODE REVIEW

**Comment by s-santillan** [comment]
@armchairlinguist 

Thank you, FYI, this has been discussed before:

image

From: https://github.com/semgrep/semgrep-docs/pull/1470/commits/0bc0eff5afeb673cf4d01a9a928061af0ef8abfd#r1556880939

**Review by s-santillan — CHANGES_REQUESTED** [review]
(Please see screenshot/comment history of previous discussion.)

**Comment by armchairlinguist** [comment]
@s-santillan - I see. The challenge with not providing this information is that we will end up providing it during debugging, and so it will probably out anyway.

Happy to discuss the best approach given the competing needs (maybe in Slack though?).

**Comment by s-santillan** [comment]
@armchairlinguist Sure, I suggest tagging Leif and Sal :)

**Pull request closed without merging**
