### PR TITLE
Update getting-started.md

### PR DESCRIPTION
**Pull request by jonweng1**
Fixing a dead link

# Thanks for improving Semgrep Docs 😀

### Please ensure

- [ ] A subject matter expert (SME) reviews the content
- [ ] A technical writer reviews the content or PR
- [x] This change has no security implications or else you have pinged the security team
- [x] Redirects are added if the PR changes page URLs
- [x] If you have changed any header tag links (doc/#this-kind-of-anchor), update all instances of that link

### CODE REVIEW

**Comment by s-santillan** [comment]
Hola @jonweng1 How'd you find this doc? It's not supposed to be listed anymore.

**Comment by jonweng1** [comment]
I searched the following: "Run Semgrep continuously"

**Comment by jonweng1** [comment]
image

**Comment by s-santillan** [comment]
@jonweng1 :ACK: I'm not sure redirects will work from Algolia. I'll remove the file directly. Thank you.

**Pull request merged**
