### PR TITLE
Add size suggestion for bitbucket

### PR DESCRIPTION
**Pull request by relsqui**
This is a suggestion from a customer who ran into this problem on several projects. Feel free to rephrase it or decide it would be better elsewhere, but I wanted to pass it along.

# Thanks for improving Semgrep Docs 😀

### Please ensure

- [ ] A subject matter expert (SME) reviews the content
- [ ] A technical writer reviews the content or PR
- [ ] This change has no security implications or else you have pinged the security team
- [ ] Redirects are added if the PR changes page URLs
- [ ] If you have changed any header tag links (doc/#this-kind-of-anchor), update all instances of that link

### CODE REVIEW

**Comment by s-santillan** [comment]
@relsqui Thank you!

Sara to add
```
options:
  size: 2x
```

code snippet when her electricity comes back.

**Review by khorne3 — APPROVED** [review]

**Comment by khorne3** [comment]
@s-santillan Sorry, I didn't see that you had looked at this already!

Do you think it's better to include the example for adding memory to the pipeline as a whole or just the step?

```
pipelines:
  default:
    - step:
        size: 2x
        script:
          - echo "This step gets double the memory!"
```

**Comment by relsqui** [comment]
Not Sara, but: IMO the step, because this has a billing impact (2x the runner size will consume 2x the minutes).

**Comment by s-santillan** [comment]
(LGTM, or nothing more for me to add, thank you @khorne3 and @relsqui )

**Pull request merged**
