### PR TITLE
Add netlify.toml file so docs serves the Docusaurus 404 page instead of Netlify’s 404 page

### PR DESCRIPTION
**Pull request by pabloest**
# Thanks for improving Semgrep Docs 😀

### Please ensure

- [ ] A subject matter expert (SME) reviews the content
- [ ] A technical writer reviews the content or PR
- [ ] This change has no security implications or else you have pinged the security team
- [ ] Redirects are added if the PR changes page URLs
- [ ] If you have changed any header tag links (doc/#this-kind-of-anchor), update all instances of that link

### CODE REVIEW

**Comment by pabloest** [comment]
Preview with this 404 URL: [https://semgrep-docs-staging.netlify.app/docs/f4343](https://semgrep-docs-staging.netlify.app/docs/f4343)

**Comment by pabloest** [comment]
CleanShot 2024-04-29 at 16 29 29

**Review by khorne3 — APPROVED** [review]

**Comment by s-santillan** [comment]
Taking the liberty of merging this...

**Comment by pabloest** [comment]
Thank you, @s-santillan.

**Pull request merged**
